# Generated by Django 4.0.2 on 2022-02-09 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_asset_options_alarmasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarmasset',
            name='saving_interval',
            field=models.IntegerField(default=1),
        ),
    ]
