# Generated by Django 4.0.2 on 2022-02-12 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alarmasset_saving_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
