# Generated by Django 4.0.2 on 2022-02-12 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_asset_category_asset_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='category',
        ),
    ]
