# Generated by Django 4.0.2 on 2022-02-14 02:04

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_asset_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarmasset',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 2, 14, 2, 4, 4, 842675, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alarmasset',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='AssetPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.asset')),
            ],
        ),
    ]
